spring:
  security:
    user:
      name: hiyoyo
      password: root
  application:
    name: security-app

server:
  port: 8080
  servlet:
    context-path: /security-app
    session:
      # http session 过期时间设置
      timeout: